# Generated by Django 6.0.1 on 2026-02-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookoutlet', '0008_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(to='bookoutlet.country'),
        ),
    ]
